runtime: go
env: standard
threadsafe: true
api_version: go1.8

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 8

handlers:
- url: /.*
  script: _go_app

inbound_services:
- mail

